export const materials = {
  aboutApp: {
    heading: "O aplikaci",
    text: "Jistě jste někdy, frustrováni odolností skvrny vůči zvolenému čistícímu prostředku, sáhli po něčem jiném. Možná jste dokonce dospěli k názoru, že čím víc, tím líp - nečistota jistě nemůže přežít zásah čtyř a více různých čističů! Neztrať hlavu! je tady pro to, aby vám prozradilo, že to občas nemusí přežít nejen flek, ale také vy. Aplikace inspirovaná hrůzou, kterou v nás vzbudily některé TikTok trendy nabádající uživatele ke zběsilému mixování všeho, co dům dal, má hráči zábavnou formou ukázat, co přesně mu hrozí, když smíchá jednu nevinně se tvářící látku s druhou, přiblížit mu reálný obsah některých komerčně dostupných čistících prostředků a připravit ho na to, že chemie je opravdu chemie i ve chvíli, kdy je prodávána s jásavou barevnou etiketou.",
  },
  layout: {
    heading: "Layout",
    text: "Hra je koncipována do jednoduchého kruhového layoutu s prvky (v našem případě obrázky dobře známých čistících prostředků). Při kliknutí na element se hráč v objevivší se tabulce dozví o tom, co čistič vlastně obsahuje za účinnou látku (všichni známe savo, ale věděli jste, že je to vlastně chlornan sodný v přestrojení?), jak jej poznat po zraku, čichu (ideálně ne po chuti), na co si dát při manipulaci s ním pozor a jakým nebezpečím se uživatel vystavuje. Hra samotná by měla probíhat pomocí drag and dropu elementů do pole uprostřed kruhu v centru obrazovky. Po přetažení dvou chemikálií na hráče vyskočí dialogové okno s vysvětlením toho, co se mu vlastně podařilo vytvořit - jestli právě přišel o ruce u loktů, poleptal si plíce, vypálil oči, nebo prostě vyrobil jenom obyčejnou kuchyňskou sůl. V případě, že se při kombinaci nestane nic, hráč si alespoň může rozšířit obzory prostřednictvím zábavného chemického faktu, který obdrží místo virtuální fyzické újmy.",
  },
  stretchGoals: {
    heading: "Stretch goals",
    text: "Za předpokladu, že by se nám aplikaci podařilo vytvořit v rekordním a dosud nevídaném čase, máme sebevědomě připraveno několik stretch goals. Rády bychom hře přidaly kodex provedených kombinací ( oranžové tlačítko v pravém horním rohu viditelné ve Figma prototypu), kde by si hráč mohl prohlédnout vše, co se mu dosud podařilo vytvořit, případně se zorientovat, které kombinace chce ještě vyzkoušet. V plánu je rovněž dodatečná gamifikace, kdy by hráč disponoval určitým množstvím životů, které by se mu za vytvoření zejména nebezpečných kombinací chemikálií odečítaly. Pokud by přišel o všechny z nich, uživatel by musel vyplnit jednoduchý tříotázkový bezpečnostní test, po kterém by se mu životy dočerpaly a on by mohl pokračovat ve hře. Ve stadiu diskuse je také lokalizace hry do jiných jazyků, spojená se zcela novými kresbami čistících prostředků typických pro daný trh.",
  },
};
